# -*- coding: utf-8 -*-
"""age calculator project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQsElB0N44TC0riD5hO0L0WgwxplK1rW
"""

def welcome():
 print("Welcome to my age calculator program")

def name():
  g = input("Input username? ")
  return g


def age(x):
  #Loop statememt
 a = int(input("Input current year? "))
 #Storing in variable to ask for the current year
 b = int(input("Input your year of birth? "))
 #Variable to ask for year of birth
 c = a - b
 #Mathematical operation to subtract the year of birth from the current year
 print(f"{x} is {c} years old")
 #Print statement to display the year of birth

def goodbye():
  print("Thank you for using my age calculator program")


welcome()
for n in range(4):
  n = name()
  age(n)
goodbye()