# -*- coding: utf-8 -*-
"""first class assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GNmWJAVYvSrO0YXXmxt1fMn_AaJw2Qgt
"""

b = float(1308)
a = input("Name of first class? ")
c = float(input("How many credits are you taking for "+ a+"? "))
d = b * c
e = input("Name of second class? ")
g = float(input("How many credits are you taking for "+ e+"? "))
h = b * g
i = input("Name of third class? ")
k = float(input("How many credits are you taking for "+ i+"? "))
n = input("Name of fourth class? ")
o = float(input("How many credits are you taking for "+ n+"? "))
p = b * o
m = b * k
print("Cost of", a, "is", d, "dollars")
print("cost of", e, "is", h, "dollars")
print("cost of", i, "is", m, "dollars")
print("cost of", n, "is", p, "dollars")
l = d + h + m + p
z = c + g + k + o
print("Your total number of credits is: ", z)
print("Your total tuition is ", l, "dollars")


#I made the cost per credit constant (line b) because the cost per credit of a school is constant and decided by the school
#I learned more about the different ways of using the print statement.
#I learned how to combine an input in a print statement just like in lines 3, 6, 9, 11, 14, 15, 16, 17, 19
#I had a challenge when I was trying to get the output of lines 3, 6, 9, and 11 to include the input of the user. i overcame this challenge by using "+"  instead of ","
#I learnt how logical python is and the different ways to write the same program to have the same output