# -*- coding: utf-8 -*-
"""Grade calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awwnXBSZufs8sZv7dPNlel5PiF5HRAmP
"""

def welcome():
  #method to welcome user to program
  print("Welcome to this grade calculator program")
  #display statemtent to welcome user


def name():
  #method to ask for student name
  a = input("Input student name? ")
  #variable to save student name and display request for student name
  return a
  #function to return variable "a"


def calc(a):
  #method to calculate average score of student
  b = float(input("Input first exam score? "))
  #function to ask for first exam score
  c = float(input("Input second exam score? "))
  #function to ask for second exam score
  d = float(input("Input third exam score? "))
  #function to ask for third exam score
  e = float(b+ c + d)
  #function to add the 3 exam scores
  f = e/3
  #function to divide the sum by 3 (finding the average)
  print(f"{a}'s average score is {f:.2f}")
  #display function to show student average score
  return f
  #returning the variable "f" from the function

def condition (a, f):
  #Method for the conditions using varibles from previous methods

  #Conditional statements to give display functions if condition is met
  if f >= 90 and f <= 100:
    print(f"{a}'s grade is A")
  elif f >=80 and f <= 89:
    print(f"{a}'s grade is B")
  elif f >=70 and f <= 79:
    print(f"{a}'s grade is C")
  elif f >=60 and f <= 69:
    print(f"{a}'s grade is D")
  elif f >= 50 and f <= 59:
    print(f"{a}'s grade is E")
  elif f >=1 and f <= 49:
    print(f"{a}'s grade is F")
  else:
    print ("Invalid score input")

def goodbye():
  #Goodbye method
  print("Thank you for using this calculator")
  #display function to Thank user


welcome()
#Calling back welcome method
for num in range(4):
  #Loop function to repeat program 4 times
  z = name()
  #Calling the name method
  x = calc(z)
  #Calling the calc method
  y = condition(z, x)
  #Calling the condition method
goodbye()
#Calling the goodbye method