# -*- coding: utf-8 -*-
"""house fee calculator project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dw3vabF4NrWIllrL-LkRQW1w-DIkm58C
"""

name = input("Input username? ")
#Asking user to input name
print("Welcome "+ name+". This program will help you calculate the breakdown of house payment")
#display welcome message with the inputted username

purchase_price = float(input("Input Purchase Price: "))
#Asking user to input the price in which he wants to purchase the house
state_tax = 0.05*purchase_price
#finding 5 percent of the purchase price, which is 0.05 multiplied by the purchase price
county_tax = 0.025*purchase_price
#finding 2.5 percent of the purchase price, which is 0.025 multiplied by the purchase price
total_price = state_tax + county_tax + purchase_price
#Adding up the tax and the initial purchase price to give the the total price
print("Your stated purchase price is: ", purchase_price)
#print(f"Your started purchase price is {purchase_price:.3f}")
#display the purchase price
print (f"County sales tax is: {county_tax:.3f}")
#display the county sales tax limited to 3 decimal places
print(f"State sales tax: {state_tax:.3f}")
#display the state sales tax limited to 3 decimal places
print(f"Your total payment(including tax) is: {total_price:.3f}")
#display the total amount to be paid excluding the realtor fee and including the tax limited to 3 decimal places
print("NOTE: county sales tax is 2.5 percent and state sales tax is 5 percent")
#display a message showing the percentage used to calculate the tax



realtor = 0.05*purchase_price
#finding 5 percent of the initial purchase price as the realtor fee
print(f"The realtor fee is: {realtor:.3f}")
#display message showing the realtor fee
print("NOTE: The realtor fee is 5 percent of initial purchase price")
#display message showing the percentage used to calculate the realtor fee
total = realtor + total_price
#sum of realtor fee plus the total amount to give the overall amount to be paid by the user
print(f"Your total payment(including tax and realtor fee) is: {total:.3f}")
#display a message showing the overall amount to be paid limited to 3 decimal places

print("Goodbye "+ name+". Thank you for using this service")
#display a goodbye message with the inputted username