# -*- coding: utf-8 -*-
"""MyGradeCaluculator for 4 Nigerians - class project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16PWftTiJUHgWmdsSu4aUoPXU2drDdXxR
"""

def welcome():
  print("Welcome to my Grade Calcultor")

def name():
  a = input("Input student name? ")
  return a


def calc(a):
  b = float(input("Input first exam score? "))
  c = float(input("Input second exam score? "))
  d = float(input("Input third exam score? "))
  e = float(b+ c + d)
  f = e/3
  print(f"{a}'s average score is {f:.2f}")
  return f


def condition (a, f):
  if f >= 90 and f <= 100:
    print(f"{a}'s grade is A")
  elif f >=80 and f <= 89:
    print(f"{a}'s grade is B")
  elif f >=70 and f <= 79:
    print(f"{a}'s grade is C")
  elif f >=60 and f <= 69:
    print(f"{a}'s grade is D")
  elif f >= 50 and f <= 59:
    print(f"{a}'s grade is E")
  elif f >=1 and f <= 49:
    print(f"{a}'s grade is F")
  else:
    print ("Invalid score input")

def goodbye():
  print("Thank you for using this calculator")
welcome()
for num in range(4):
  z = name()
  x = calc(z)
  y = condition(z, x)
goodbye()