# -*- coding: utf-8 -*-
"""class pocket project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOutX7ULvOC2bXTQ4zgNVo7NnehNClSb
"""

name = input("Input Username? ")
#Input function used to ask the user to input username
print("Welcome", name)
#function to display a welcome message to also include the inputted username
pocket = int(input("Input Pocket number on Wheel after spinning....  "))
#function to ask user to input the pocket number after spinning the wheel


def even():
#defining a conditional function to indicate whether a number is even or odd
 if pocket%2 == 0:
#an if statement to tell if a number is even because when even numbers are divided by 2, the remainder is 0, which is why the "%" sign is used because it deals with remainder after dividing
      print("Black Pocket")
#A follow up print statement to display if the if condition is satisfied
 else:
#An else statement to tell colab what to do if the opposite of the if statement is satisfied
      print("Red Pocket")
#A display function if the else condition is satisfied


def odd():
#defining a conditional function to indicate whether a number is odd or even
  if pocket%2 != 0:
#an if statement to tell if a number is odd because when odd numbers are divided by 2, there is a remainder, which is why the "%" sign is used because it deals with remainder after dividing
      print("Black Pocket")
#A follow up print statement to display if the if condition is satisfied
  else:
#An else statement to tell colab what to do if the opposite of the if statement is satisfied
      print("Red Pocket")
#A display function if the else condition is satisfied

if pocket < 0 or pocket > 36:
#An if statement to indicate a range of numbers
  print ("Invalid pocket number")
#A display function to state what happens if the "if" statement is satisfied
else:
#An else statement to state what happens if the opposite of the if statement is satisfied
  if pocket >= 1 and pocket <= 10:
#A follow-up if statement indented under the else statement to restrict a particular display to a range
    even()
#Recalling the initially defined method called even

  elif pocket >= 11 and pocket <= 18:
#A follow-up elif statement indented under the else statement to restrict a particular display to a range
    odd()
#Recalling the initially defined method called odd

  elif pocket >= 19 and pocket <= 28:
#A follow-up elif statement indented under the else statement to restrict a particular display to a range
    even()
#Recalling the initially defined method called even

  elif pocket >= 29 and pocket <= 36:
#A follow-up elif statement indented under the else statement to restrict a particular display to a range
    odd()
#Recalling the initially defined method called odd

  elif pocket == 0:
#A follow-up elif statement indented under the else statement to restrict a particular display to a range
    print("Green Pocket")
#A print statement for a display for when this elif statement is satisfied


print("Goodbye "+name)
#A goodbye display message